from __future__ import annotations

from typing import Any, Dict, TypedDict

from langgraph.graph import StateGraph, START, END

from tools.data_processor import process_engineering_data
from tools.engineering_analysis import perform_engineering_analysis
from tools.knowledge_retrieval import retrieve_technical_knowledge
from tools.constraint_checker import check_engineering_constraints
from tools.cpp_validation import run_cpp_validation
from tools.safety_consistency import validate_analysis_result


class AgentState(TypedDict, total=False):
    case: Dict[str, Any]
    plan: Dict[str, Any]
    processed: Dict[str, Any]
    knowledge: Dict[str, Any]
    analysis: Dict[str, Any]
    constraints: Dict[str, Any]
    cpp: Dict[str, Any]
    validation: Dict[str, Any]
    result: Dict[str, Any]


def build_graph():
    """
    Build the local engineering-validation execution graph.

    IMPORTANT:
    The graph does NOT create a new LLM plan.

    A plan must already be supplied in the initial state.
    This is required for model evaluation so that the plan
    generated by Nemotron is the plan that gets
    evaluated locally.
    """

    graph = StateGraph(AgentState)

    # ---------------------------------------------------------
    # PLAN INPUT
    # ---------------------------------------------------------

    def plan_node(state: AgentState):
        """
        Preserve the model-generated plan supplied by the caller.

        No LLM call is performed here.
        """

        plan = state.get("plan")

        if not isinstance(plan, dict):
            raise RuntimeError(
                "No valid model-generated plan was supplied "
                "to the local execution graph."
            )

        return {
            "plan": plan,
        }

    # ---------------------------------------------------------
    # PROCESS INPUT
    # ---------------------------------------------------------

    def process_node(state: AgentState):
        """
        Validate and normalize the engineering input.
        """

        processed = process_engineering_data.invoke(
            {
                "case": state["case"],
            }
        )

        return {
            "processed": processed,
        }

    # ---------------------------------------------------------
    # KNOWLEDGE RETRIEVAL
    # ---------------------------------------------------------

    def knowledge_node(state: AgentState):
        """
        Retrieve relevant engineering knowledge locally.
        """

        case = state["case"]

        query = (
            f"Beam engineering validation for material "
            f"{case.get('material')}, load, dimensions, "
            f"allowable stress, and bending stress constraints."
        )

        knowledge = retrieve_technical_knowledge.invoke(
            {
                "query": query,
            }
        )

        return {
            "knowledge": knowledge,
        }

    # ---------------------------------------------------------
    # ENGINEERING ANALYSIS
    # ---------------------------------------------------------

    def analysis_node(state: AgentState):
        """
        Perform the engineering calculation using PyTorch.
        """

        analysis = perform_engineering_analysis.invoke(
            {
                "data": state["processed"],
            }
        )

        return {
            "analysis": analysis,
        }

    # ---------------------------------------------------------
    # CONSTRAINT CHECK
    # ---------------------------------------------------------

    def constraint_node(state: AgentState):
        """
        Check calculated stress against allowable stress.
        """

        constraints = check_engineering_constraints.invoke(
            {
                "analysis": state["analysis"],
                "data": state["processed"],
            }
        )

        return {
            "constraints": constraints,
        }

    # ---------------------------------------------------------
    # C++ VALIDATION
    # ---------------------------------------------------------

    def cpp_node(state: AgentState):
        """
        Run the independent C++ engineering validation.
        """

        cpp = run_cpp_validation.invoke(
            {
                "data": state["processed"],
            }
        )

        return {
            "cpp": cpp,
        }

    # ---------------------------------------------------------
    # FINAL VALIDATION
    # ---------------------------------------------------------

    def validation_node(state: AgentState):
        """
        Perform deterministic safety and consistency validation.
        """

        validation = validate_analysis_result.invoke(
            {
                "processed": state["processed"],
                "analysis": state["analysis"],
                "constraints": state["constraints"],
                "cpp": state["cpp"],
            }
        )

        knowledge_documents = []

        knowledge = state.get(
            "knowledge",
            {},
        )

        if isinstance(knowledge, dict):

            knowledge_results = knowledge.get(
                "results",
                [],
            )

            if isinstance(
                knowledge_results,
                list,
            ):

                knowledge_documents = [
                    item["document"]
                    for item in knowledge_results
                    if isinstance(item, dict)
                    and "document" in item
                ]

        result = {
            "case_id": state["case"]["case_id"],
            "material": state["case"]["material"],
            "plan": state.get("plan", {}),
            "analysis": state["analysis"],
            "constraints": state["constraints"],
            "cpp_validation": state["cpp"],
            "safety_consistency": validation,
            "knowledge_documents": knowledge_documents,
            "final_status": (
                "VALID"
                if validation["status"] == "PASS"
                else "INVALID"
            ),
        }

        return {
            "validation": validation,
            "result": result,
        }

    # ---------------------------------------------------------
    # NODES
    # ---------------------------------------------------------

    graph.add_node(
        "plan",
        plan_node,
    )

    graph.add_node(
        "process",
        process_node,
    )

    graph.add_node(
        "knowledge",
        knowledge_node,
    )

    graph.add_node(
        "analysis",
        analysis_node,
    )

    graph.add_node(
        "constraints",
        constraint_node,
    )

    graph.add_node(
        "cpp",
        cpp_node,
    )

    graph.add_node(
        "validation",
        validation_node,
    )

    # ---------------------------------------------------------
    # EXECUTION FLOW
    # ---------------------------------------------------------

    graph.add_edge(
        START,
        "plan",
    )

    graph.add_edge(
        "plan",
        "process",
    )

    graph.add_edge(
        "process",
        "knowledge",
    )

    graph.add_edge(
        "knowledge",
        "analysis",
    )

    graph.add_edge(
        "analysis",
        "constraints",
    )

    graph.add_edge(
        "constraints",
        "cpp",
    )

    graph.add_edge(
        "cpp",
        "validation",
    )

    graph.add_edge(
        "validation",
        END,
    )

    return graph.compile()